#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'Debian GNU/Linux with Finit' --class debian --class gnu-linux --class gnu --class os --user {
	insmod gzio
	insmod part_msdos
	insmod ext2
	set root='(hd0,0)'
	search --no-floppy --fs-uuid --set=root  05831a47-bf7c-4812-9cb2-818537aa68fc
	linux	/vmlinuz root=UUID=05831a47-bf7c-4812-9cb2-818537aa68fc ro quiet init=/sbin/finit
	initrd	/initrd.img
}
