#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry '$MENU with Finit' --class $TYPE --class gnu-linux --class gnu --class os --user {
	insmod gzio
	insmod part_msdos
	insmod ext2
	search --no-floppy --fs-uuid --set=root $BOOT
	linux	/vmlinuz root=UUID=$ROOT ro quiet init=/sbin/finit
	initrd	/initrd.img
}
